name: CI
on: push

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v3
        - run: npm install
        - run: npx hardhat test
